In [1]:
import pandas as pd
import os
import csv
import requests


# Join Netflix_titles.csv
csvpath1 = os.path.join('..','Netflix Project', 'netflix_titles.csv')
with open(csvpath1, 'r', encoding='utf-8') as csvfile:
    csvreader = csv.reader(csvfile, delimiter=',')
    for row in csvreader:
        print(row)

FileNotFoundError: [Errno 2] No such file or directory: '../Netflix Project/netflix_titles.csv'

In [ ]:
netflix = pd.read_csv(csvpath1)
print("Null or NaN values")
print(netflix.isnull().sum())

Null or NaN values
show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
API_KEY = 'cc5b24bf'

def search_movie_country(movie_title):
    url = f'http://www.omdbapi.com/?apikey={API_KEY}&t={movie_title}'
    response = requests.get(url)
    data = response.json()
    if 'Country' in data:
        return data['Country']
    return None

# Filter country rows
missing_country_df = netflix[netflix['country'].isna()]

# Extract Titles [Movies / TV Shows] that have NaN
missing_country_movies = missing_country_df[missing_country_df['type'] == 'Movie']['title'].tolist()
missing_country_shows = missing_country_df[missing_country_df['type'] == 'TV Show']['title'].tolist()

# New empty DataFrame to store the new data
new_data = []

# API request to fetch country information for missing movies
for movie_title in missing_country_movies:
    country = search_movie_country(movie_title)
    if country:
        new_data.append({'title': movie_title, 'country': country})

# API request to fetch country information for missing TV shows
for show_title in missing_country_shows:
    country = search_movie_country(show_title)
    if country:
        new_data.append({'title': show_title, 'country': country})

# Convert the new data into a DataFrame
new_df = pd.DataFrame(new_data)
# Missing values in

In [ ]:
# Confirm there are no NaN/Null in the newdf

print(new_df.isnull().sum())

title      0
country    0
dtype: int64

In [ ]:
# Merge `updated_df` with `new_df` on 'title' column
updated_df = updated_df.merge(new_df, on='title', how='left', suffixes=('', '_new'))

# Drop the extra 'country_new' column
updated_df.drop('country_new', axis=1, inplace=True)

updated_df

,show_id,type,title,director,cast,country_x,date_added,release_year,rating,duration,listed_in,description,country_y,country
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,,United States,"September 25, 2021",2020.0,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",NaN,NaN
1,s2,TV Show,Blood & Water,,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",NaN,NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",,"September 24, 2021",2021.0,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,France,NaN
3,s4,TV Show,Jailbirds New Orleans,,,,"September 24, 2021",2021.0,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",United States,NaN
4,s5,TV Show,Kota Factory,,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9338,NaN,NaN,ViR: The Robot Boy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,India
9339,NaN,NaN,Wake Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States
9340,NaN,NaN,Yoko,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Germany, Austria, Sweden"
9341,NaN,NaN,YOM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Egypt
9342,NaN,NaN,Zombie Dumb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,South Korea

In [ ]:
print(updated_df.isnull().sum())

show_id          536
type             536
title              0
director         536
cast             536
country_x        536
date_added       536
release_year     536
rating           536
duration         536
listed_in        536
description      536
country_y       8807
country         8807
dtype: int64